/**
 * User profile row from the `profiles` table.
 * Created automatically via Supabase trigger on `auth.users` insert.
 */
export interface Profile {
  id: string
  full_name: string | null
  phone: string | null
  streak_current?: number
  streak_longest?: number
  streak_last_completed_date?: string | null
  created_at: string
}

/**
 * A study subject (e.g., "Physics", "History").
 * One user → many subjects. The sentinel subject "Others" (`STANDALONE_SUBJECT_ID`)
 * holds uncategorized standalone tasks.
 */
export interface Subject {
  id: string
  user_id: string
  name: string
  sort_order: number
  archived: boolean
  deadline: string | null
  created_at: string
}

/**
 * A chapter or sub-topic within a subject (e.g., "Chapter 4: Kinematics").
 * One subject → many topics. Topics carry planning parameters used by the
 * scheduling engine (session length, rest days, dependencies, etc.).
 */
export interface Topic {
  id: string
  user_id: string
  subject_id: string
  name: string
  sort_order: number
  archived: boolean
  estimated_hours?: number
  deadline?: string | null
  earliest_start?: string | null
  depends_on?: string[]
  session_length_minutes?: number
  rest_after_days?: number
  max_sessions_per_day?: number
  study_frequency?: string
  created_at: string
}

/**
 * A scheduled or manual task. Tasks can be generated by the planner engine
 * (`task_source: "plan"`, linked to a `plan_snapshot_id`) or created manually
 * (`task_source: "manual"`). Canonical intake tasks (`session_number: 0`,
 * `total_sessions: 1`, no snapshot) seed the planner but are excluded from UI.
 */
export interface Task {
  id: string
  user_id: string
  subject_id: string | null
  topic_id: string | null
  title: string
  task_type: "subject" | "standalone"
  scheduled_date: string
  duration_minutes: number
  session_type: "core" | "revision" | "practice"
  session_number?: number
  total_sessions?: number
  sort_order?: number
  completed: boolean
  task_source: "manual" | "plan"
  plan_snapshot_id: string | null
  source_topic_task_id?: string | null
  created_at: string
}

/**
 * A sub-task template row from the `topic_tasks` table.
 * Belongs to a topic and represents a pre-defined unit of work
 * that the planner can schedule independently.
 */
export interface TopicTask {
  id: string
  user_id: string
  subject_id: string
  topic_id: string
  title: string
  duration_minutes: number
  completed: boolean
  sort_order: number
  created_at: string
  updated_at?: string
}

/**
 * A serialized plan snapshot stored in the `plan_snapshots` table.
 * Created atomically via the `commit_plan_atomic_v2` RPC.
 * `schedule_json` contains the full plan output; `settings_snapshot`
 * captures the planner constraints at commit time for later comparison.
 */
export interface PlanSnapshot {
  id: string
  user_id: string
  task_count: number
  schedule_json: unknown
  settings_snapshot: unknown
  summary: string | null
  created_at: string
}
